import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";
import logo from "../../public/logo.svg";
import Container from "react-bootstrap/Container";
import Button from "react-bootstrap/Button";
import Stack from "react-bootstrap/Stack";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Welcome to Getiff",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className="navigation">
          <Stack direction="horizontal" gap={3}>
            <Link href="/" className="me-auto">
              <Image
                src={logo}
                width={111}
                height={42}
                alt="Picture of the author"
                className="logo"
              />
            </Link>
            <Link href="/join-our-community" className="btn btn-outline-primary">Join our Community</Link>
            <Link href="/onboarding" className="btn btn-primary">Register Now</Link>
          </Stack>
        </nav>
        
        {children}
      </body>
    </html>
  );
}
